# Generated by Django 4.2.1 on 2023-05-08 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('title', '0002_remove_title_likes_entry_likers_alter_title_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='dislikers',
            field=models.ManyToManyField(blank=True, related_name='dislikers', to=settings.AUTH_USER_MODEL),
        ),
    ]
