# Generated by Django 4.2.1 on 2023-05-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0003_entry_dislikers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=models.TextField(max_length=500),
        ),
    ]
